title: Stoltz Stack
description: Web development resources and tools
baseurl: ""
url: "https://stoltzstack.com"

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Plugins
plugins:
  - jekyll-feed

# Collections
collections:
  tools:
    output: true
  blog:
    output: true

# Default front matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

# Feed settings
feed:
  path: feed.xml 